all: 6_1_ex clean

6_1_ex: main.obj myStack.obj tests.obj workingWithData.obj
	cl main.obj myStack.obj tests.obj workingWithData.obj

main.obj: main.cpp
	cl -c main.cpp /EHsc

myStack.obj: myStack.cpp
	cl -c myStack.cpp /EHsc

tests.obj: tests.cpp
	cl -c tests.cpp /EHsc

workingWithData.obj: workingWithData.cpp
	cl -c workingWithData.cpp /EHsc


clean:
	del main.obj myStack.obj tests.obj workingWithData.obj